import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "title": "Happy Shop",
          "explanation": "The right address for your shopping",
          "skip": "Skip",
          "user_login": "User Login",
          "admin_login": "Admin  Login",
          "continue_without_login": "Continue Without Login",
          "your_informaiton": "YOUR INFORMATION",
          "bodySize": "Body Size",
          "shoeSize": "Shoe Size",
          "okey": "OKEY",
          "userPage": "USER PAGE",
          "adminPage": "ADMIN PAGE",
          "login": "Login",
          "register": "REGİSTER",
          "kullaniciGirisi": "USER LOGIN",
          "eposta": "E posta",
          "password": "password",
          "enter": "ENTER",
          "sıgnIn": "SIGIN IN",
          "adminLogin": "ADMIN LOGIN",
          "adminPanel": "ADMIN PANEL",
          "urunName": "Product Name: ",
          "create": "CREATE",
          "update": "UPDATE",
          "delete": "DELETE",
          "product_added":"Product Added",
          "product_updated":"Product Updated",
          "product_deleted":"Product Deleted",
          "kategori": "Categori: ",
          "home ": "Home",
          "admin": "Admin",
          "exit": "Exit",
          "size":"Size: ",
          "bodysec":"Clothes",
          "shoesec":"Shoes"
          
    

        },
        'tr_TR': {
          "title": "MUTLU ALIŞVERİŞ",
          "explanation": "Alışveriş için doğru adrestesiniz",
          "skip": "Atla",
          "user_login": "Kullanıcı girişi",
          "admin_login": "Yönetici girişi",
          "continue_without_login": "giriş yapmadan devam et",
          "your_informaiton": "bilgilerinizi giriniz",
          "bodySize": "Beden: ",
          "shoeSize": "Ayakkabı Num: ",
          "okey": "TAMAM",
          "userPage": "KULLANICI SAYFASI",
          "adminPage": "YÖNETİCİ SAYFASI",
          "login": "Giriş",
          "kullaniciGirisi": "KULLANICI GİRİŞİ",
          "eposta": "E posta",
          "password": "Şifre",
          "enter": "GİRİŞ",
          "register": "KAYIT OL",
          "sıgnIn": "KAYIT",
          "adminLogin": "YÖNETİCİ GİRİŞİ",
          "adminPanel": "ADMIN PANEL",
          "urunName": "Ürün Adı: ",
          "create": "OLUŞTUR",
          "update": "GÜNCELLE",
          "delete": "SİL",
          "product_added":"Ürün Eklendi",
          "product_updated":"Ürün Güncellendi",
          "product_deleted":"Ürün Silindi",
          "veriler": "VERİLER",
          "kategori": "Kategori: ",
          "home ": "Ana Sayfa",
          "admin": "Yönetici",
          "exit": "Çıkış",
          "size":"Numara: ",
          "bodysec":"Kıyafet",
          "shoesec":"Ayakkabı"
          
        }
      };
}
