// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV72HDxU1pPPnQQjRexGX6GF-SnDT8n00',
    appId: '1:810316875234:web:5ecf0952531719ef7b25bb',
    messagingSenderId: '810316875234',
    projectId: 'fir-eticaret-project',
    authDomain: 'fir-eticaret-project.firebaseapp.com',
    storageBucket: 'fir-eticaret-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVt6dx6uVP0RXfWDLcIUR22e4G-URfZs',
    appId: '1:810316875234:android:5287204608b0692a7b25bb',
    messagingSenderId: '810316875234',
    projectId: 'fir-eticaret-project',
    storageBucket: 'fir-eticaret-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0KE9IwkGlYPH6KIjF7HHpv1dFstZNII',
    appId: '1:810316875234:ios:e5225f11659da7f97b25bb',
    messagingSenderId: '810316875234',
    projectId: 'fir-eticaret-project',
    storageBucket: 'fir-eticaret-project.appspot.com',
    iosClientId: '810316875234-aso6n7ogc2cd9dhs4l0quqpbat14ucbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.eticaretProject',
  );
}
